
cask_args appdir: '/Applications'
tap 'Homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
brew 'autoconf'
brew 'cask'
brew 'cloog'
brew 'coreutils'
brew 'gcc'
brew 'gmp'
brew 'isl'
brew 'libmpc'
brew 'mpfr'
brew 'gh'
brew 'node'
brew 'nodenv'
brew 'wget'
cask 'dropbox'
cask 'firefox'
cask 'dockutil'
cask 'google-chrome'
cask 'iterm2'
cask '1password'
cask 'rectangle'
cask 'font-menlo-for-powerline'
cask 'font-hack'
cask 'visual-studio-code'
