
cask_args appdir: '/Applications'
tap 'Homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
brew 'autoconf'
brew 'cask'
brew 'cloog'
brew 'coreutils'
brew 'gcc'
brew 'gmp'
# brew 'dockutil'
brew 'isl'
brew 'libmpc'
brew 'mpfr'
# brew 'mysql'
brew 'gh'
brew 'node'
# brew 'nvm'
# brew 'openssl'
# brew 'ossp-uuid'
# brew 'pkg-config'
# brew 'postgresql'
# brew 'rbenv'
# brew 'readline'
# brew 'ruby-build'
brew 'wget'
cask 'dropbox'
cask 'firefox'
# cask 'google-chrome'
# cask 'iterm2'
# cask '1password'
# cask 'rectangle'
# cask 'transmission'
# cask 'vlc'
cask 'font-menlo-for-powerline'
cask 'font-hack'
cask 'visual-studio-code'
