tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "autoconf"
brew "gmp"
brew "coreutils"
brew "cask"
brew "isl"
brew "cloog"
brew "mpfr"
brew "libmpc"
brew "gcc"
brew "gh"
brew "jq"
brew "mas"
brew "ruby-build"
brew "rbenv"
brew "node"
brew "nodenv"
brew "nvm"
brew "n"
brew "wget"
cask "1password"
cask "google-chrome"
cask "dockutil"
cask "caffeine"
cask "dropbox"
cask "finicky"
cask "firefox"
cask "font-hack"
cask "discord"
cask "spotify"
cask "karabiner-elements"
cask "notion"
cask "font-menlo-for-powerline"
cask "iterm2"
cask "obsidian"
cask "rectangle"
cask "visual-studio-code"
mas "Things", id: 904280696
mas "Fantastical", id: 975937182
mas "Slack", id: 803453959
mas "Save to Raindrop.io", id: 1549370672
